### PR TITLE
Fix NameError (uninitialized constant Pushover::VERSION)

### PR DESCRIPTION
**Pull request by masutaka**
Fix the following error:

```
$ irb
irb(main):001:0> require 'pushover'
Traceback (most recent call last):
        9: from /Users/masutaka/.rbenv/versions/2.6.3/bin/irb:23:in `<main>'
        8: from /Users/masutaka/.rbenv/versions/2.6.3/bin/irb:23:in `load'
        7: from /Users/masutaka/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        6: from (irb):1
        5: from /Users/masutaka/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        4: from /Users/masutaka/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        3: from /Users/masutaka/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
        2: from /Users/masutaka/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/pushover-3.0.0/lib/pushover.rb:9:in `<top (required)>'
        1: from /Users/masutaka/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/pushover-3.0.0/lib/pushover.rb:11:in `<module:Pushover>'
NameError (uninitialized constant Pushover::VERSION)
```

### CODE REVIEW

**Comment by erniebrodeur** [comment]
the question is, I thought I had a version check in the spec.   I'll fix this tomorrow @masutaka it's 3am for me, but will merge and push by monday.  if you figure out why the spec didn't fail with no version, and fix that, I'll merge right away, else I need to debug the spec.

**Comment by masutaka** [comment]
The reason is for the following spec:

https://github.com/erniebrodeur/pushover/blob/v3.0.0/spec/lib/pushover_spec.rb#L3-L7

**Comment by masutaka** [comment]
Sorry, the above is wrong. The spec doesn't fail for the following:

https://github.com/erniebrodeur/pushover/blob/v3.0.0/pushover.gemspec#L1

**Comment by erniebrodeur** [comment]
image

**Comment by erniebrodeur** [comment]
in the future, can you work off dev?   it's trick for me to do that through master, thanks.

**Comment by masutaka** [comment]
> in the future, can you work off dev? it's trick for me to do that through master, thanks.

Does that mean you want me to create a pull request to the `development` branch? It's ok.

**Comment by erniebrodeur** [comment]
yes, thank you, I can make a release from there.   right now, I have to move it there, then release.

if it's just documentation, typos, things that do not require a version bump, master is fine.

this is pretty common.    thank you for your understanding

**Pull request closed without merging**
